### ISSUE TITLE
Results could be better?

### ISSUE THREAD

**Issue by alirezazareian** [ericjang/draw#10]
I have been playing with this code for a few days. I can reproduce the GIF animation showed in the first page of this repository. However, this other implementation based on theano (https://github.com/jbornschein/draw) achieves much (subjectively) nicer results (look at their GIF animation). I have tried to use their parameters (like T=64 and read_window=2) in the tensorflow code but I was unable to reproduce results that look that nice. Do you have any idea why there is such a difference and how we can achieve results like that using this tensorflow code?

By niceness I mean the animation looks more realistic, which probably means what the model learns is closer to the actual causal process that happens in human handwriting.

**Comment by alirezazareian** [comment]
Figured! The problem is that canvases are initialized to zeros. But after sigmoid, zero becomes 0.5 which means gray. Since the model starts from a gray canvas, it has to paint the character with white AND the background with black. Simply initializing canvases to -6 instead of zero, now it starts with a black background and beautifully draws digits like a human does. Setting read_window=2 and T=32 helps.

**Comment by ericjang** [comment]
Radical, thanks! Sorry, I don't really have time to investigate bugs in my OSS projects...
