### ISSUE TITLE
Filterbank has minor error

### ISSUE THREAD

**Issue by Razcle** [ericjang/draw#11]
Hi Eric,

thanks for this implementation! Its been hugely useful in replicating the paper. One thing that I noticed is that in the filterbank function you're squaring the entire exponent rather than just the numerator which is what you want. 

i/e your filters are slightly off from equations 24 and 25 in the paper.

Thanks!

Raza

**Comment by ericjang** [comment]
Thanks Raza! Fixed in https://github.com/ericjang/draw/commit/56bb9404bc3d01da1e1ed2930660221f8c39f7b0
