### ISSUE TITLE
mu_x typo?

### ISSUE THREAD

**Issue by xxi511** [ericjang/draw#3]
Not issue, just out of curious

```
grid_i = tf.reshape(tf.cast(tf.range(N), tf.float32), [1, -1])    
mu_x = gx + (grid_i - N / 2 - 0.5) * delta # eq 19
```

if `N` = 3, `delta = 1`
`grid_i` will be `[0 1 2]` 
then `grid_i - N / 2` is `grid_i - 1. = [-1 0 1]`
then `grid_i - N / 2 - 0.5` is `[-1.5 -0.5 0.5]`

but I think `[-1 0 1]` is reasonable value, the mean location will be `[gx-1, gx, gx+1]`
why need to subtract 0.5, just follow the paper or I miss something?
thanks

**Comment by ericjang** [comment]
It's been awhile since I wrote this code & read the paper, but I believe `grid_i` is actually indexed starting at 1. So `grid_i - N/2 - 0.5 is [-1,0,1]`. This means there is a mistake in my code ;)
