### ISSUE TITLE
How to open npy file?

### ISSUE THREAD

**Issue by Raj-08** [ericjang/draw#4]
How to open npy file?

**Comment by ericjang** [comment]
```
import numpy as np
a = np.load('/path/to/file.npy')
print(a)
```

**Comment by Raj-08** [comment]
Hi Eric,

I am a researcher / developer from bangalore india.

Have you ever thought about how an inverse DRAW model would work?

**Comment by ericjang** [comment]
No

**Comment by Raj-08** [comment]
what do you do?

**Comment by piyush0407** [comment]
import numpy as np
b=np.load('/path/to/file.npy')
print(b)
but  the error is directory not find
