### ISSUE TITLE
kl divergence computation

### ISSUE THREAD

**Issue by Atomu2014** [ericjang/draw#8]
Thanks for sharing this elegant DRAW model!

However, I found in kl divergence computation in draw.py, line 191, the last term should be 0.5 instead of 0.5*T according to the paper's equation 11.

Even though this constant term won't affect the optimization process, I think you may get a different but reasonable loss curve. Because in this situation, it is possible to get negative KL divergence.

Thanks!

**Comment by ericjang** [comment]
thanks for the catch. fixed.

**Comment by Celia0** [comment]
"Because in this situation, it is possible to get negative KL divergence." I'm playing with a pytorch version of DRAW. May I ask this means it will avoid a negative KL divergence or it will cause a negative KL divergence~? Thanks a lot!
